# Lobby Inventory
Lobby:
  Vote:
    item: 'compass:0'
    slot: 0
    name: '&aVotar'
    lore: [ ]
    action: 'voteMenu:none'
  Teams:
    item: 'leather_helmet:0'
    slot: 1
    name: '&bElegir Equipo'
    need: 'ptc.chooseteam'
    lore: [ ]
    action: 'teamsMenu:none'
  Statistics:
    item: 'paper:0'
    slot: 7
    name: '&e&lEstad√≠sticas'
    lore: [ ]
    action: 'statisticsMenu:none'
  Leave:
    item: 'iron_door:0'
    slot: 8
    name: '&cSalir'
    lore: [ ]
    action: 'leave:none'