# Lobby Inventory
Lobby:
  Vote:
    item: 'compass:0'
    slot: 0
    name: '&aVotar'
    lore: [ ]
    action: 'voteMenu:none'
  Teams:
    item: 'leather_helmet:0'
    slot: 1
    name: '&bElegir Equipo'
    need: 'ptc.chooseteam'
    lore: [ ]
    action: 'teamsMenu:none'
  Extras:
    item: 'nether_star:0'
    slot: 4
    name: '&6&lExtras'
    lore: [ ]
    action: 'extrasMenu:none'
  Leave:
    item: 'iron_door:0'
    slot: 8
    name: '&cSalir'
    lore: [ ]
    action: 'leave:none'